import type { AdaxTrainingRecord } from "../types";

const RECORD_EXPORT_BOUNDARY =
  "This file is generated by a local training sandbox and does not represent real market settlement.";
const RECORDS_EXPORT_BOUNDARY =
  "These records are generated by a local training sandbox and do not represent real market settlement.";

export function buildRecordExportJson(record: AdaxTrainingRecord) {
  return JSON.stringify(
    {
      exportType: "ADAX_TRAINING_RECORD",
      exportedAt: new Date().toISOString(),
      boundary: RECORD_EXPORT_BOUNDARY,
      record
    },
    null,
    2
  );
}

export function buildRecordsExportJson(records: AdaxTrainingRecord[]) {
  return JSON.stringify(
    {
      exportType: "ADAX_TRAINING_RECORDS",
      exportedAt: new Date().toISOString(),
      count: records.length,
      boundary: RECORDS_EXPORT_BOUNDARY,
      records
    },
    null,
    2
  );
}
